/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package StartProgramFrame;

/**
 *
 * @author Blanco
 */
public class StartProgramFrame extends javax.swing.JFrame {

    /**
     * Creates new form java
     */
    public StartProgramFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setText("Start Game");
        getContentPane().add(jButton1);
        jButton1.setBounds(430, 420, 87, 23);

        jButton2.setText("Quit");
        getContentPane().add(jButton2);
        jButton2.setBounds(550, 420, 53, 23);

        jTextField1.setText("Enter your name");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(420, 390, 190, 20);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DuchessOfDamascus/pictures/This is the one.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(300, 20, 400, 350);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DuchessOfDamascus/pictures/Background.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-430, 0, 1150, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            StartProgramFrame.util.logging.Logger.getLogger(StartProgramFrame.class.getName()).log(StartProgramFrame.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            StartProgramFrame.util.logging.Logger.getLogger(StartProgramFrame.class.getName()).log(StartProgramFrame.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            StartProgramFrame.util.logging.Logger.getLogger(StartProgramFrame.class.getName()).log(StartProgramFrame.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            StartProgramFrame.util.logging.Logger.getLogger(StartProgramFrame.class.getName()).log(StartProgramFrame.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        StartProgramFrame.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartProgramFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
